### ISSUE TITLE
Upgrade to L4T 31.1

### ISSUE THREAD

**Issue by dantwinkler** [balena-os/balena-jetson-tx2#118]
Looking to upgrade to the latest L4T.  Wondering if you had a rough timeline of when you expect to have an upgrade to the latest L4T 32.1 which includes an updated 4.9 kernel.  More details below.

https://docs.nvidia.com/jetson/archives/jetpack-archived/jetpack-411/index.html#jetpack/4.1.1/release_notes.htm%3FTocPath%3D_____2

https://docs.nvidia.com/jetson/l4t/pdf/Tegra_Linux_Driver_Package_Release_Notes_R31.1.pdf

**Comment by floion** [comment]
Hi, we have a wip for tx2 on latets L4T here: https://github.com/balena-os/balena-jetson-nano/issues/10
It's a different repo so you could build it and test it on your side. We are waiting on a fix from NVidia before we officially release it though
