### ISSUE TITLE
bluetooth not functional on jetson tx2

### ISSUE THREAD

**Issue by floion** [balena-os/balena-jetson-tx2#129]
https://forums.balena.io/t/bluetooth-service-dead-on-jetson-tx2-cti-orbitty/6229

**Comment by tintinp** [comment]
Hello,

I also receive the same error
```
root@16c2a6e:~# modprobe btusb
modprobe: FATAL: Module btusb not found in directory /lib/modules/4.4.38-l4t-r28.1+g79e4600
```

Is this why when I tried `hcitool dev`, it returned no device?

```
root@16c2a6e:~# hcitool dev 
Devices:
```

Thank you

**Comment by pdcastro** [comment]
At least two users have reported this issue. Gathering some data:
* The device works with Jetpack 3.3 ***without balenaOS:***
  * `lsmod` shows that bluetooth is used by `bnep` and `hci_uart`.
  * `hcitool dev` show a device.
  * Bluetooth works fine.
* But does not work with balenaOS 2.31.5+rev1 (development, SKX2 beta):
  * `journalctl -u bluetooth` does not show any log entries.
  * `hcitool dev` does not show any devices.
  * `modprobe btusb` gives `"modprobe: FATAL: Module btusb not found in directory /lib/modules/4.4.38-l4t-r28.1+g79e4600"`
  * `rfkill` output:
```
root@a1c7bde:~# rfkill unblock bluetooth
root@a1c7bde:~# rfkill list
0: bluedroid_pm: bluetooth
Soft blocked: no
Hard blocked: no
1: phy0: wlan
Soft blocked: no
Hard blocked: no
2: brcmfmac-wifi: wlan
Soft blocked: no
Hard blocked: no
root@a1c7bde:~# systemctl start bluetooth
root@a1c7bde:~# systemctl status bluetooth
● bluetooth.service - Bluetooth service
Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
Active: inactive (dead)
Docs: man:bluetoothd(8)
```

**Comment by pdcastro** [comment]
I understand that this issue is resolved by pull request #133, which is included in balenaOS **v2.33.0+rev3** or later. At the time of this writing, our [staging environment](https://dashboard.balena-staging.com/) had release v2.33.0+rev4 available (being tested), while the production environment is still at 2.31.2+rev1. So the fix is coming to production soon.

**Comment by tintinp** [comment]
Thank you for you help

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-jetson-tx2/pull/155
