### ISSUE TITLE
CTI spacely carrier board

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-jetson-tx2#74]
yocto name: spacely-tx2
slug: spacely-tx2
pretty name: "CTI Spacely TX2"

**Comment by floion** [comment]
We'll use the DTB which supports IMX274 6 Cameras

**Comment by floion** [comment]
Implemented by https://github.com/resin-os/resin-jetson-tx2/pull/76

**Comment by drjasonharrison-vp-eio** [comment]
@floion can this issue be closed?

**Comment by floion** [comment]
@drjasonharrison-vp-eio yes this can be closed
